include:
  - sitemap.xml
  - feed.xml
  - robots.txt
  - llms.txt
  - google60465e62c5fccd47.html
  - .nojekyll

exclude: []

url: "https://rafi10merch-alt.github.io"
baseurl: "/carrd-promo-codes-2026"
